### ISSUE TITLE
какая информация должна быть размещена здесь

### ISSUE THREAD

**Issue by rashtug2** [Seykes/bep20-unstake_withdraw#1]
withdrawalAddress := common.HexToAddress("") //этот адрес контракта всегда указывается при выводе

**Comment by rashtug2** [comment]
the error is///             w3: call failed: execution reverted

**Comment by Spice9009** [comment]
this code keeps saying call failed. any fix?

**Comment by Seykes** [comment]
This code is an example implementation. Unfortunately, I cannot provide a full-fledged version of this application, because the project is relevant and operates in the hands of a private person

**Comment by Seykes** [comment]
The repository itself was created as an example of the implementation of such a project, due to the fact that I received a lot of questions about the implementation of such

**Comment by rashtug2** [comment]
i have already work it out, thanks anyway
